# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dbQueries as Db
from Admin_Pages.invalidUsernamePassword import Ui_InvalidUsernamePassword as invUserPass
from Admin_Pages.insertUpdateDelete import Ui_MainWindow as insUpdDel

class Ui_AdminAuthorization(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Username = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")
        self.horizontalLayout.addWidget(self.Username)
        self.UsernameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameLineEdit.setObjectName("UsernameLineEdit")
        self.horizontalLayout.addWidget(self.UsernameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Password = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Password.setFont(font)
        self.Password.setObjectName("Password")
        self.horizontalLayout_2.addWidget(self.Password)
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.PasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_2.addWidget(self.PasswordLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Ok_for_username = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Ok_for_username.setFont(font)
        self.Ok_for_username.setObjectName("Ok_for_username")
        self.horizontalLayout_3.addWidget(self.Ok_for_username)
        self.Back_for_username = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Back_for_username.setFont(font)
        self.Back_for_username.setObjectName("Back_for_username")
        self.horizontalLayout_3.addWidget(self.Back_for_username)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.duplicateMain=MainWindow
        # When the user clicks the Ok button on the window-
        self.Ok_for_username.clicked.connect(self.authorize)
        # When the user clicks the Back button on the window-
        self.Back_for_username.clicked.connect(lambda :MainWindow.close())

    def authorize(self):
        uname=self.UsernameLineEdit.text()
        passw=self.PasswordLineEdit.text()
        res=Db.verifyUser(uname,passw)
        # print(res)
        if len(res)==1:
            try:
                self.insertUpdateDeleteForm = QtWidgets.QMainWindow()
                self.insertUpdateDeleteUi = insUpdDel()
                self.insertUpdateDeleteUi.setupUi(self.insertUpdateDeleteForm,uname)
                self.insertUpdateDeleteForm.show()
                self.duplicateMain.close()
            except Exception as e:
                print(e)
        else:
            self.invalidUsernamePasswordForm = QtWidgets.QMainWindow()
            self.invUi = invUserPass()
            self.invUi.setupUi(self.invalidUsernamePasswordForm)
            self.invalidUsernamePasswordForm.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOGIN"))
        self.Username.setText(_translate("MainWindow", "Username"))
        self.Password.setText(_translate("MainWindow", "Password"))
        self.Ok_for_username.setText(_translate("MainWindow", "Ok"))
        self.Back_for_username.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminAuthorization()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
