# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dbQueries as Db
from Admin_Pages.transactionstatus import Ui_transactionSuccessful as transactionStatus

class Ui_DeleteWindow(object):
    def setupUi(self, MainWindow,type):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deleteForm = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.deleteForm.setFont(font)
        self.deleteForm.setObjectName("deleteForm")
        self.verticalLayout.addWidget(self.deleteForm)
        spacerItem = QtWidgets.QSpacerItem(20, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enter = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.horizontalLayout.addWidget(self.enter)
        self.idForDeletion = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.idForDeletion.setFont(font)
        self.idForDeletion.setObjectName("idForDeletion")
        self.horizontalLayout.addWidget(self.idForDeletion)
        self.deletIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.deletIdLineEdit.setObjectName("deletIdLineEdit")
        self.horizontalLayout.addWidget(self.deletIdLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 122, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.okForDeletion = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.okForDeletion.setFont(font)
        self.okForDeletion.setObjectName("okForDeletion")
        self.horizontalLayout_2.addWidget(self.okForDeletion)
        self.backForDeletion = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.backForDeletion.setFont(font)
        self.backForDeletion.setObjectName("backForDeletion")
        self.horizontalLayout_2.addWidget(self.backForDeletion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.idForDeletion.setText(str(type).upper()+" ID")

        self.type = type
        self.okForDeletion.clicked.connect(lambda: self.evaluate(type,MainWindow))
        self.backForDeletion.clicked.connect(lambda: MainWindow.close())

    def evaluate(self, type,MainWindow):
        if type == 'plane':
            res = Db.deletePlane(self.deletIdLineEdit.text())
        elif type == 'train':
            res = Db.deleteTrain(self.deletIdLineEdit.text())
        elif type == 'bus':
            res = Db.deleteBus(self.deletIdLineEdit.text())
        elif type == 'hotel':
            res = Db.deleteHotel(self.deletIdLineEdit.text())
        if (res == 1):
            self.tranForm = QtWidgets.QMainWindow()
            self.tranUi = transactionStatus()
            self.tranUi.setupUi(self.tranForm,1)
            self.tranForm.show()

        else:
            self.tranForm = QtWidgets.QMainWindow()
            self.tranUi = transactionStatus()
            self.tranUi.setupUi(self.tranForm,-1)
            self.tranForm.show()
        MainWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Delete Entry"))
        self.deleteForm.setText(_translate("MainWindow", "              Delete An Entry-"))
        self.enter.setText(_translate("MainWindow", "Enter"))
        self.idForDeletion.setText(_translate("MainWindow", "XXYY ID"))
        self.okForDeletion.setText(_translate("MainWindow", "Ok"))
        self.backForDeletion.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_DeleteWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
