# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hotel_insert_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dbQueries as Db
from Admin_Pages.transactionstatus import Ui_transactionSuccessful as transactionStatus

class Ui_hotelWindow(object):
    def setupUi(self, MainWindow,type):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hotelInsertUpdateForm = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hotelInsertUpdateForm.setFont(font)
        self.hotelInsertUpdateForm.setAlignment(QtCore.Qt.AlignCenter)
        self.hotelInsertUpdateForm.setObjectName("hotelInsertUpdateForm")
        self.verticalLayout_3.addWidget(self.hotelInsertUpdateForm)
        spacerItem = QtWidgets.QSpacerItem(777, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.hotelName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hotelName.setFont(font)
        self.hotelName.setObjectName("hotelName")
        self.verticalLayout.addWidget(self.hotelName)
        self.localityID = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.localityID.setFont(font)
        self.localityID.setObjectName("localityID")
        self.verticalLayout.addWidget(self.localityID)
        self.rating = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rating.setFont(font)
        self.rating.setObjectName("rating")
        self.verticalLayout.addWidget(self.rating)
        self.streetAddress = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.streetAddress.setFont(font)
        self.streetAddress.setObjectName("streetAddress")
        self.verticalLayout.addWidget(self.streetAddress)
        self.roomService = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roomService.setFont(font)
        self.roomService.setObjectName("roomService")
        self.verticalLayout.addWidget(self.roomService)
        self.contactNumber = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contactNumber.setFont(font)
        self.contactNumber.setObjectName("contactNumber")
        self.verticalLayout.addWidget(self.contactNumber)
        self.totalAvailableRooms = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalAvailableRooms.setFont(font)
        self.totalAvailableRooms.setObjectName("totalAvailableRooms")
        self.verticalLayout.addWidget(self.totalAvailableRooms)
        self.cost = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cost.setFont(font)
        self.cost.setObjectName("cost")
        self.verticalLayout.addWidget(self.cost)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hotelNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hotelNameLineEdit.setFont(font)
        self.hotelNameLineEdit.setObjectName("hotelNameLineEdit")
        self.verticalLayout_2.addWidget(self.hotelNameLineEdit)
        self.localityIDLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.localityIDLineEdit.setFont(font)
        self.localityIDLineEdit.setObjectName("localityIDLineEdit")
        self.verticalLayout_2.addWidget(self.localityIDLineEdit)
        self.ratingLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ratingLineEdit.setFont(font)
        self.ratingLineEdit.setObjectName("ratingLineEdit")
        self.verticalLayout_2.addWidget(self.ratingLineEdit)
        self.streetAddressLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.streetAddressLineEdit.setObjectName("streetAddressLineEdit")
        self.verticalLayout_2.addWidget(self.streetAddressLineEdit)
        self.roomServiceLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.roomServiceLineEdit.setObjectName("roomServiceLineEdit")
        self.verticalLayout_2.addWidget(self.roomServiceLineEdit)
        self.contactNumberLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.contactNumberLineEdit.setObjectName("contactNumberLineEdit")
        self.verticalLayout_2.addWidget(self.contactNumberLineEdit)
        self.totalAvailableRoomsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalAvailableRoomsLineEdit.setFont(font)
        self.totalAvailableRoomsLineEdit.setObjectName("totalAvailableRoomsLineEdit")
        self.verticalLayout_2.addWidget(self.totalAvailableRoomsLineEdit)
        self.costLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.costLineEdit.setFont(font)
        self.costLineEdit.setObjectName("costLineEdit")
        self.verticalLayout_2.addWidget(self.costLineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 83, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hotelInsertUpdateOkButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hotelInsertUpdateOkButton.setFont(font)
        self.hotelInsertUpdateOkButton.setObjectName("hotelInsertUpdateOkButton")
        self.horizontalLayout_3.addWidget(self.hotelInsertUpdateOkButton)
        self.hotelInsertUpdateBackButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hotelInsertUpdateBackButton.setFont(font)
        self.hotelInsertUpdateBackButton.setObjectName("hotelInsertUpdateBackButton")
        self.horizontalLayout_3.addWidget(self.hotelInsertUpdateBackButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.type = type
        self.hotelInsertUpdateOkButton.clicked.connect(lambda: self.evaluate(type))
        self.hotelInsertUpdateBackButton.clicked.connect(lambda: MainWindow.close())

    def evaluate(self, type):
        if type == 'insert':
            # print("Balle")
            if self.hotelNameLineEdit.text() != '' and self.localityIDLineEdit.text() != '' and self.ratingLineEdit.text() != '' \
                    and self.streetAddressLineEdit.text() != '' and self.roomServiceLineEdit.text() != '' and self.contactNumberLineEdit.text() != '' \
                    and self.totalAvailableRoomsLineEdit.text() != '' and self.costLineEdit.text() != '':
                res = Db.insertHotel(self.hotelNameLineEdit.text(), self.localityIDLineEdit.text(),
                                     self.ratingLineEdit.text(), self.streetAddressLineEdit.text(),
                                     self.roomServiceLineEdit.text(), self.contactNumberLineEdit.text(),
                                     self.totalAvailableRoomsLineEdit.text(), self.costLineEdit.text())
                if (res == 1):
                    self.tranForm = QtWidgets.QMainWindow()
                    self.tranUi = transactionStatus()
                    self.tranUi.setupUi(self.tranForm,1)
                    self.tranForm.show()
                else:
                    self.tranForm = QtWidgets.QMainWindow()
                    self.tranUi = transactionStatus()
                    self.tranUi.setupUi(self.tranForm,-1)
                    self.tranForm.show()
        elif type == 'update':
            if self.hotelNameLineEdit.text() != '' and self.localityIDLineEdit.text() != '' and self.ratingLineEdit.text() != '' \
                    and self.streetAddressLineEdit.text() != '' and self.roomServiceLineEdit.text() != '' \
                    and self.contactNumberLineEdit.text() != '' and self.totalAvailableRoomsLineEdit.text() != ''\
                    and self.costLineEdit.text() != '':
                res = Db.updateHotel(self.hotelNameLineEdit.text(), self.localityIDLineEdit.text(),
                                     self.ratingLineEdit.text(), self.streetAddressLineEdit.text(),
                                     self.roomServiceLineEdit.text(), self.contactNumberLineEdit.text(),
                                     self.totalAvailableRoomsLineEdit.text(), self.costLineEdit.text())

                if (res == 1):
                    self.tranForm = QtWidgets.QMainWindow()
                    self.tranUi = transactionStatus()
                    self.tranUi.setupUi(self.tranForm,1)
                    self.tranForm.show()
                else:
                    self.tranForm = QtWidgets.QMainWindow()
                    self.tranUi = transactionStatus()
                    self.tranUi.setupUi(self.tranForm,-1)
                    self.tranForm.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hotel Details"))
        self.hotelInsertUpdateForm.setText(_translate("MainWindow", "HOTEL INSERT/ UPDATE FORM-"))
        self.hotelName.setText(_translate("MainWindow", "Hotel Name"))
        self.localityID.setText(_translate("MainWindow", "Locality ID"))
        self.rating.setText(_translate("MainWindow", "Rating"))
        self.streetAddress.setText(_translate("MainWindow", "Street Address"))
        self.roomService.setText(_translate("MainWindow", "Room Service"))
        self.contactNumber.setText(_translate("MainWindow", "Contact Number"))
        self.totalAvailableRooms.setText(_translate("MainWindow", "Total Available Rooms"))
        self.cost.setText(_translate("MainWindow", "Cost"))
        self.hotelInsertUpdateOkButton.setText(_translate("MainWindow", "Ok"))
        self.hotelInsertUpdateBackButton.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_hotelWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
