# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hotel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hotelInformation(object):
    def setupUi(self, Form,result1,parent):
        Form.setObjectName("Form")
        Form.resize(1360, 900)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.banner = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.banner.sizePolicy().hasHeightForWidth())
        self.banner.setSizePolicy(sizePolicy)
        self.banner.setText("")
        self.banner.setPixmap(QtGui.QPixmap("ImageFile/hotel.gif"))
        self.banner.setScaledContents(True)
        self.banner.setObjectName("banner")
        self.verticalLayout.addWidget(self.banner)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.backbtn = QtWidgets.QPushButton(Form)
        self.backbtn.setObjectName("backbtn")
        self.horizontalLayout.addWidget(self.backbtn)
        self.okbtn = QtWidgets.QPushButton(Form)
        self.okbtn.setAutoDefault(True)
        self.okbtn.setDefault(False)
        self.okbtn.setObjectName("okbtn")
        self.horizontalLayout.addWidget(self.okbtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #resize header to window size
        header=self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)

        self.tableWidget.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)

        self.tableWidget.clicked.connect(self.selectPlace)

        self.movie=QtGui.QMovie('ImageFile/hotel.gif')
        self.banner.setMovie(self.movie)
        self.movie.start()

        self.row=0

        self.result1=result1

        self.tableWidget.setRowCount(len(self.result1))

        for index, val in enumerate(self.result1):
            for col in range(7):
                cell = QtWidgets.QTableWidgetItem(str(val[col]))
                self.tableWidget.setItem(index, col, cell)

        self.okbtn.clicked.connect(lambda:self.hotelSelectedOk(parent,Form))

        self.backbtn.clicked.connect(lambda:Form.close())

    def hotelSelectedOk(self,parent,Form):
        parent.hotelFlag=True
        parent.hotelSelected=self.result1[self.row]
        Form.close()

    def selectPlace(self,clickedIndex):
        self.row=clickedIndex.row()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hotels"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "HOTEL NAME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "AVAILABLE NO. OF ROOMS"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "RATING"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "is AC"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "COST"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "MOBILE NO"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "ADDRESS"))
        self.backbtn.setText(_translate("Form", "BACK"))
        self.okbtn.setText(_translate("Form", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_hotelInformation()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
