# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'placeInformation2.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import dbQueries as Db
from imagerViewer import Ui_image_view as imgViewer
from getCityName import Ui_cityForm as cityName
from transportationServices import Ui_transportationWindow as transportationWindow
from hotelInformation import Ui_hotelInformation as hotelInfo
from summary import Ui_Form as summaryUI
from promtWindow import Ui_Form as promtClass

class Ui_Form(object):
    def setupUi(self, Form,pinfo,scity,dcity,selType):
        Form.setObjectName("Form")
        Form.resize(1360, 900)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bannerpic = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bannerpic.sizePolicy().hasHeightForWidth())
        self.bannerpic.setSizePolicy(sizePolicy)
        self.bannerpic.setText("")
        self.bannerpic.setPixmap(QtGui.QPixmap("../ImageFile/roadMoving.gif"))
        self.bannerpic.setScaledContents(True)
        self.bannerpic.setObjectName("bannerpic")
        self.verticalLayout_6.addWidget(self.bannerpic)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.place_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Castellar")
        font.setPointSize(24)
        self.place_name.setFont(font)
        self.place_name.setObjectName("place_name")
        self.verticalLayout.addWidget(self.place_name)
        self.place_type = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Bradley Hand ITC")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.place_type.setFont(font)
        self.place_type.setScaledContents(True)
        self.place_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.place_type.setWordWrap(True)
        self.place_type.setObjectName("place_type")
        self.verticalLayout.addWidget(self.place_type)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.photosbtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(119)
        sizePolicy.setHeightForWidth(self.photosbtn.sizePolicy().hasHeightForWidth())
        self.photosbtn.setSizePolicy(sizePolicy)
        self.photosbtn.setMinimumSize(QtCore.QSize(0, 0))
        self.photosbtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.photosbtn.setSizeIncrement(QtCore.QSize(7, 54))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.photosbtn.setFont(font)
        self.photosbtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.photosbtn.setAutoFillBackground(True)
        self.photosbtn.setDefault(True)
        self.photosbtn.setFlat(False)
        self.photosbtn.setObjectName("photosbtn")
        self.horizontalLayout.addWidget(self.photosbtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(31)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.description = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(66)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.description.setFont(font)
        self.description.setAutoFillBackground(True)
        self.description.setFrameShape(QtWidgets.QFrame.Box)
        self.description.setScaledContents(True)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout_2.addWidget(self.description)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(True)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.address = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address.sizePolicy().hasHeightForWidth())
        self.address.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setFamily("Bell MT")
        self.address.setFont(font)
        self.address.setScaledContents(True)
        self.address.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.address.setObjectName("address")
        self.horizontalLayout_2.addWidget(self.address)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.entryfee = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryfee.sizePolicy().hasHeightForWidth())
        self.entryfee.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setFamily("Bell MT")
        self.entryfee.setFont(font)
        self.entryfee.setObjectName("entryfee")
        self.horizontalLayout_3.addWidget(self.entryfee)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.rating = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(23)
        self.rating.setFont(font)
        self.rating.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rating.setScaledContents(True)
        self.rating.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rating.setWordWrap(True)
        self.rating.setObjectName("rating")
        self.horizontalLayout_4.addWidget(self.rating)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.hotelbtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotelbtn.sizePolicy().hasHeightForWidth())
        self.hotelbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.hotelbtn.setFont(font)
        self.hotelbtn.setObjectName("hotelbtn")
        self.verticalLayout_3.addWidget(self.hotelbtn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.transportationbtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transportationbtn.sizePolicy().hasHeightForWidth())
        self.transportationbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.transportationbtn.setFont(font)
        self.transportationbtn.setObjectName("transportationbtn")
        self.verticalLayout_4.addWidget(self.transportationbtn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.summarybtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summarybtn.sizePolicy().hasHeightForWidth())
        self.summarybtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.summarybtn.setFont(font)
        self.summarybtn.setObjectName("summarybtn")
        self.verticalLayout_5.addWidget(self.summarybtn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #
        self.roadgif=QtGui.QMovie('ImageFile/roadmoving.gif')
        self.bannerpic.setMovie(self.roadgif)
        self.roadgif.start()
        self.scity=scity
        self.dcity=dcity

        self.pinfo=list(pinfo)

        self.transportFlag=False
        self.hotelFlag=False

        self.placeInfo=pinfo
        self.selType=selType
        self.photosbtn.clicked.connect(self.showPlaceImages)

        self.place_name.setText("<font color=#ed6a24>"+str(self.placeInfo[0])+"</font>")
        self.place_type.setText(str(self.placeInfo[1]))
        self.description.setText("<font color=#522f75>"+str(self.placeInfo[2])+"</font>")
        self.rating.setText(str(self.placeInfo[4]))
        self.entryfee.setText("Rs."+str(self.placeInfo[5]))
        self.address.setText(str(self.placeInfo[3]))

        self.hotelbtn.clicked.connect(self.LoadHotelWin)

        self.transportationbtn.clicked.connect(self.transportationServices)

        self.summarybtn.clicked.connect(self.summaryFetcher)

    def showPlaceImages(self):
            self.form4=QtWidgets.QWidget()
            self.viewer=imgViewer()
            self.viewer.setupUi(self.form4,str(self.placeInfo[0]))
            self.form4.show()

    def LoadHotelWin(self):
        try:
            self.locality=Db.getLocality(self.placeInfo[0])
            self.hotelsList=Db.getHotels(self.locality)
            self.hotelInfoForm = QtWidgets.QWidget()
            self.formUi = hotelInfo()
            self.formUi.setupUi(self.hotelInfoForm,self.hotelsList,parent=self)
            self.hotelInfoForm.show()
        except Exception as e:
            print(e)


    def summaryFetcher(self):
        if self.hotelFlag is True and self.transportFlag is True:
            self.summaryForm = QtWidgets.QWidget()
            self.formUi = summaryUI()
            self.formUi.setupUi(self.summaryForm,self.pinfo,self.hotelSelected,self.transportSelected)
            self.summaryForm.show()
        elif self.hotelFlag is False or self.transportFlag is False:
            self.promtWin=QtWidgets.QWidget()
            self.promtUi=promtClass()
            self.promtUi.setupUi(self.promtWin)
            self.promtWin.show()


    def transportationServices(self):
        try:
            if self.selType == 1:
                self.cityform=QtWidgets.QWidget()
                self.formUi=cityName()
                self.formUi.setupUi(self.cityform,parent=self)
                self.cityform.show()
            else:
                self.form6=QtWidgets.QWidget()
                self.pinfo.append(self.scity)
                self.transportWindow=transportationWindow()
                self.transportWindow.setupUi(self.form6,self.scity,self.dcity,parent=self)
                self.form6.show()
        except Exception as e:
            print(e)

    def execmethod(self):
        try:
             self.scity=str(self.formUi.srccombo.currentText()).upper()
             self.pinfo.append(self.scity)
             self.form5=QtWidgets.QWidget()
             self.transportWindow=transportationWindow()
             self.transportWindow.setupUi(self.form5,self.scity,self.dcity,parent=self)
             self.cityform.close()
             self.form5.show()
             print('ok')
        except Exception as e:
            print(e)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.place_name.setText(_translate("Form", "Place Name"))
        self.place_type.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Place Type</span></p></body></html>"))
        self.photosbtn.setText(_translate("Form", "Click here for PHOTOS"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Description :</span></p></body></html>"))
        self.description.setText(_translate("Form", "<html><head/><body><p>Place description, address, facility</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Address :</span></p></body></html>"))
        self.address.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Value</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Entry Fee :</span></p></body></html>"))
        self.entryfee.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Value</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Rating : </span></p></body></html>"))
        self.rating.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">value</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Available Hotels:</span></p></body></html>"))
        self.hotelbtn.setText(_translate("Form", "HOTELS"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Available Transportation:</span></p></body></html>"))
        self.transportationbtn.setText(_translate("Form", "TRANSPORTATION"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Get Summary :</span></p></body></html>"))
        self.summarybtn.setText(_translate("Form", "SUMMARY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
