# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\summary.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form,pinfo,hotelSelected,transportSelected):
        Form.setObjectName("Form")
        Form.setFixedSize(1360, 900)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(4)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.place_name = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.place_name.sizePolicy().hasHeightForWidth())
        self.place_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.place_name.setFont(font)
        self.place_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.place_name.setObjectName("place_name")
        self.horizontalLayout_9.addWidget(self.place_name)
        self.place_type = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.place_type.sizePolicy().hasHeightForWidth())
        self.place_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.place_type.setFont(font)
        self.place_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.place_type.setObjectName("place_type")
        self.horizontalLayout_9.addWidget(self.place_type)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.place_address = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.place_address.sizePolicy().hasHeightForWidth())
        self.place_address.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.place_address.setFont(font)
        self.place_address.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.place_address.setObjectName("place_address")
        self.horizontalLayout_7.addWidget(self.place_address)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.place_rating = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.place_rating.sizePolicy().hasHeightForWidth())
        self.place_rating.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.place_rating.setFont(font)
        self.place_rating.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.place_rating.setObjectName("place_rating")
        self.horizontalLayout_8.addWidget(self.place_rating)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_30 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_10.addWidget(self.label_30)
        self.place_cost = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.place_cost.sizePolicy().hasHeightForWidth())
        self.place_cost.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.place_cost.setFont(font)
        self.place_cost.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.place_cost.setObjectName("place_cost")
        self.horizontalLayout_10.addWidget(self.place_cost)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_17.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, 3, 0)
        self.horizontalLayout_6.setSpacing(23)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.vehicle_type = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicle_type.sizePolicy().hasHeightForWidth())
        self.vehicle_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.vehicle_type.setFont(font)
        self.vehicle_type.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vehicle_type.setMidLineWidth(0)
        self.vehicle_type.setObjectName("vehicle_type")
        self.horizontalLayout_6.addWidget(self.vehicle_type)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vehicle_name = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicle_name.sizePolicy().hasHeightForWidth())
        self.vehicle_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.vehicle_name.setFont(font)
        self.vehicle_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vehicle_name.setObjectName("vehicle_name")
        self.verticalLayout_4.addWidget(self.vehicle_name)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.from_city = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_city.sizePolicy().hasHeightForWidth())
        self.from_city.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.from_city.setFont(font)
        self.from_city.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.from_city.setObjectName("from_city")
        self.horizontalLayout.addWidget(self.from_city)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.label_14 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.to_city = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_city.sizePolicy().hasHeightForWidth())
        self.to_city.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.to_city.setFont(font)
        self.to_city.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.to_city.setObjectName("to_city")
        self.horizontalLayout_4.addWidget(self.to_city)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_20)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.ddate = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ddate.sizePolicy().hasHeightForWidth())
        self.ddate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.ddate.setFont(font)
        self.ddate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ddate.setObjectName("ddate")
        self.horizontalLayout_2.addWidget(self.ddate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.dtime = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtime.sizePolicy().hasHeightForWidth())
        self.dtime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.dtime.setFont(font)
        self.dtime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dtime.setObjectName("dtime")
        self.horizontalLayout_3.addWidget(self.dtime)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_31 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_15.addWidget(self.label_31)
        self.transportation_cost = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transportation_cost.sizePolicy().hasHeightForWidth())
        self.transportation_cost.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.transportation_cost.setFont(font)
        self.transportation_cost.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transportation_cost.setObjectName("transportation_cost")
        self.horizontalLayout_15.addWidget(self.transportation_cost)
        spacerItem4 = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_22 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_22.setFont(font)
        self.label_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_23 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.hotel_name = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotel_name.sizePolicy().hasHeightForWidth())
        self.hotel_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.hotel_name.setFont(font)
        self.hotel_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotel_name.setObjectName("hotel_name")
        self.horizontalLayout_11.addWidget(self.hotel_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_25 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        self.hotel_address = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotel_address.sizePolicy().hasHeightForWidth())
        self.hotel_address.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.hotel_address.setFont(font)
        self.hotel_address.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotel_address.setObjectName("hotel_address")
        self.horizontalLayout_12.addWidget(self.hotel_address)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_27 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_13.addWidget(self.label_27)
        self.hotel_rating = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotel_rating.sizePolicy().hasHeightForWidth())
        self.hotel_rating.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.hotel_rating.setFont(font)
        self.hotel_rating.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotel_rating.setObjectName("hotel_rating")
        self.horizontalLayout_13.addWidget(self.hotel_rating)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_32 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_16.addWidget(self.label_32)
        self.hotel_cost = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotel_cost.sizePolicy().hasHeightForWidth())
        self.hotel_cost.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.hotel_cost.setFont(font)
        self.hotel_cost.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotel_cost.setObjectName("hotel_cost")
        self.horizontalLayout_16.addWidget(self.hotel_cost)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.total_cost = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_cost.sizePolicy().hasHeightForWidth())
        self.total_cost.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.total_cost.setFont(font)
        self.total_cost.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.total_cost.setScaledContents(False)
        self.total_cost.setIndent(-1)
        self.total_cost.setObjectName("total_cost")
        self.verticalLayout_9.addWidget(self.total_cost)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #
        self.place_name.setText(str(pinfo[0]))
        self.place_type.setText(str(pinfo[1]))
        self.place_address.setText(str(pinfo[3]))
        self.place_rating.setText(str(pinfo[4]))
        self.place_cost.setText(str(pinfo[5]))

        self.vehicle_name.setText(str(transportSelected[0]))
        self.vehicle_type.setText(str(transportSelected[4]))
        self.from_city.setText(str(transportSelected[5]))
        self.to_city.setText(str(transportSelected[6]))
        self.ddate.setText(str(transportSelected[1]))
        self.dtime.setText(str(transportSelected[2]))
        self.transportation_cost.setText(str(transportSelected[3]))

        self.hotel_name.setText(str(hotelSelected[0]))
        self.hotel_address.setText(str(hotelSelected[6]))
        self.hotel_rating.setText(str(hotelSelected[2]))
        self.hotel_cost.setText(str(hotelSelected[4])+" / Day")

        self.summation=float(pinfo[5])+float(transportSelected[3])+float(hotelSelected[4])
        self.total_cost.setText("<html><head/><body><p><span style=\" color:#080cff;\">The Total cost Per Person for this combination made would be approximately = ₹ {}</span></p></body></html>".format(str(self.summation)))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Summary "))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#590cff;\">Summary</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aa007f;\">Place Selected</span></p></body></html>"))
        self.place_name.setText(_translate("Form", "Place Name"))
        self.place_type.setText(_translate("Form", "place Type"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">Address:</span></p></body></html>"))
        self.place_address.setText(_translate("Form", "vv puram,kr road Bengaluru"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">Rating:</span></p></body></html>"))
        self.place_rating.setText(_translate("Form", "4.3"))
        self.label_30.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">COST:</span></p></body></html>"))
        self.place_cost.setText(_translate("Form", "Cost"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aa007f;\">Transportation Selected</span></p></body></html>"))
        self.vehicle_type.setText(_translate("Form", "-Train/Bus/Plane"))
        self.vehicle_name.setText(_translate("Form", "Vehicle Name"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">From:</span></p></body></html>"))
        self.from_city.setText(_translate("Form", "Bengaluru"))
        self.label_14.setText(_translate("Form", "To:"))
        self.to_city.setText(_translate("Form", "Mumbai"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">Departure Date:</span></p></body></html>"))
        self.ddate.setText(_translate("Form", "20/08/2021"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">Departure Time:</span></p></body></html>"))
        self.dtime.setText(_translate("Form", "08:30 AM"))
        self.label_31.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">COST:</span></p></body></html>"))
        self.transportation_cost.setText(_translate("Form", "Cost"))
        self.label_22.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aa007f;\">Hotel Selected</span></p></body></html>"))
        self.label_23.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">Hotel Name:</span></p></body></html>"))
        self.hotel_name.setText(_translate("Form", "Trip Planner Hotel"))
        self.label_25.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">Address:</span></p></body></html>"))
        self.hotel_address.setText(_translate("Form", "Karnataka, India"))
        self.label_27.setText(_translate("Form", "Rating:"))
        self.hotel_rating.setText(_translate("Form", "8.3"))
        self.label_32.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55557f;\">COST:</span></p></body></html>"))
        self.hotel_cost.setText(_translate("Form", "cost"))
        self.total_cost.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#080cff;\">The Total cost Per Person for this combination made would be approximately =</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
